#
# Setup travis for java, it auto detects gradle for most parts
#
language: java
sudo: false # use false for faster builds?

#
# Ensure haveged is installed, and env is properly setup
#
addons:
  apt:
    packages:
    - haveged
before_script:
  #- sudo apt-get install haveged
  # - service haveged start
  # Trick java into using urandom, I do not need
  # enterprise security for unit testing
  # See : https://github.com/travis-ci/travis-ci/issues/1494
  - "export JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
  # Ensure build permission for various files
  - chmod +x gradlew
#
# Build / Test scripts
#
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew buildAll
  # - ./gradlew jar
  # - ./gradlew shadowJar
  # - ./gradlew fatJar
  
#
# Caching - to be used if relevent
#
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
#
# Code coverage run
#
after_success:
  - bash <(curl -s https://codecov.io/bash)